### ISSUE TITLE
Error on Github with latest version

### ISSUE THREAD

**Issue by Anahkiasen** [omigos/HubHarvester#14]
```
Refused to load the script 'https://platform.harvestapp.com/assets/platform.js' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".
(program):1 (anonymous function)
extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Cannot read property 'innerHTML' of undefined
    at GitLab.parseElement (chrome-extension://nfjjpilhlncfoehpfhomhhadieegecgn/data/index.js:194:70)
    at GitLab.refresh (chrome-extension://nfjjpilhlncfoehpfhomhhadieegecgn/data/index.js:216:40)
    at TrackingPage.refresh (chrome-extension://nfjjpilhlncfoehpfhomhhadieegecgn/data/index.js:95:37)
    at Object.callback (chrome-extension://nfjjpilhlncfoehpfhomhhadieegecgn/data/index.js:27:64)
    at chrome-extension://nfjjpilhlncfoehpfhomhhadieegecgn/data/index.js:1:21extensions::uncaught_exception_handler:8 handler
```

**Comment by Anahkiasen** [comment]
Space dedicated to the button appears but not the button itself

**Comment by MassiveHiggsField** [comment]
Could you please provide some more information? Which OS are you using and are you using any other security related extensions? What are your settings for this extension? It seems that there are 2 problems here (probably related). First of, the extension thinks you are using GitLab instead of GitHub and the other, it doesn'T seem to add the CSP policy to allow loading scripts from harvest.com.

**Comment by MassiveHiggsField** [comment]
Nevermind, found the bug. Pushing now, will release 2.0.2 soon.
